CHN EQU P3.7
ADC_ALE EQU P3.6
ADC_START EQU P3.5
ADC_EOC EQU P3.3
ADC_OE EQU P3.4
ADC_PORT EQU P2
M1 EQU P1.0
M2 EQU P1.1
CLK EQU P3.2

ORG 0000H
LJMP MAIN
ORG 001BH
LJMP ISR_CLOCK

ORG 0050H
MAIN:
MOV IE,#88H
MOV TMOD,#20H
MOV TH1,#-100
SETB TR1

MOV P0,#01110111B
MOV P1,#0
HERE:
MOV R0,#0
MOV R1,#0
MOV A,#0
CLR CHN              ;SELECT CHANNEL 0
CLR ADC_ALE          ;ALE PIN LOW
CLR ADC_START        ;START PIN LOW                   
CALL DELAY_SMALL
SETB ADC_ALE         ;ALE PIN HIGH
CALL DELAY_SMALL
SETB ADC_START       ;START PIN HIGH
CALL DELAY_SMALL
CLR ADC_ALE          ;ALE PIN LOW
CALL DELAY_SMALL;
CLR ADC_START        ;START PIN LOW
A1:JNB ADC_EOC,A1
SETB ADC_OE
MOV A,ADC_PORT
;CLR ADC_OE
MOV R0,A

SETB CHN              ;SELECT CHANNEL 7
CLR ADC_ALE          ;ALE PIN LOW
CLR ADC_START        ;START PIN LOW                   
CALL DELAY_SMALL
SETB ADC_ALE         ;ALE PIN HIGH
CALL DELAY_SMALL
SETB ADC_START       ;START PIN HIGH
CALL DELAY_SMALL
CLR ADC_ALE          ;ALE PIN LOW
CALL DELAY_SMALL
CLR ADC_START        ;START PIN LOW
A2:JNB ADC_EOC,A2
SETB ADC_OE
MOV A,ADC_PORT
;CLR ADC_OE
MOV R1,A

SUBB A,R0
JZ HERE
JC MM1
JNC MM2

SJMP HERE

MM1:
CLR C
SETB M1
ACALL DELAY

CLR M1
LJMP HERE
MM2:
SETB M2
ACALL DELAY

CLR M2
LJMP HERE

DELAY_SMALL:
 MOV R4,#001H
JJ5: MOV R5,#01FH
JJ6: DJNZ R5,JJ6
 DJNZ R4,JJ5
 RET
 
DELAY:
 MOV R4,#0FH
JJ1: MOV R5,#05FH
JJ2: DJNZ R5,JJ2
 DJNZ R4,JJ1
 RET
 
 ISR_CLOCK:
 CPL CLK
 RETI
END